rubyatscale/packs-rails

README.md
The paths listed in the README imply that the `config/initializers` and `lib/tasks` folders should be placed within the `app` directory in the package's folder, when they should belong in the root of the package directory.  This PR corrects the spacing in the README and moves the lines down slightly to make the markdown more readable.
=> Correcting the path structure listed in the README

README.md, lib/stimpack.rb
We'd like to keep routes in the pack they belong. In order to achieve that, we'll need to also add the `config/routes/` dir for each pack to the Rails paths.
This features is based on the Rails feature to [break up very large route file into multiple small ones](https://guides.rubyonrails.org/routing.html#breaking-up-very-large-route-file-into-multiple-small-ones).
We're not sure if this PR can affect the Engine setup, besides that, its usage is optional so it shouldn't impact anyone.
You can see an example of this feature implemented [here](https://github.com/rootstrap/rails-modular-monolith-with-ddd/pull/23).
=> Add the ability to define routes per pack

lib/stimpack/integrations/rspec.rb
Instead of only checking the `::RSpec` module, also verify we have a method named `configuration` to use.
=> Check if ::RSpec has a method named configuration

lib/stimpack/packs.rb, lib/stimpack/railtie.rb, lib/stimpack/version.rb, spec/fixtures/rails-7.0/packs/pants/shorts/app/models/shorts/zipper.rb, spec/fixtures/rails-7.0/packs/pants/shorts/app/services/shorts/khaki.rb, spec/fixtures/rails-7.0/packs/pants/shorts/app/services/shorts/linen.rb, spec/stimpack_spec.rb, test/test_helper.rb
This PR allows stimpack to support one-level-deep nested packs.
- Remove minitest
- add clarifying comment
- Add new tests and functionality
- Bump verson
=> Add functionality for nested packs

lib/stimpack/packs.rb, lib/stimpack/version.rb
Now that Stimpack supports nested packs :partying_face:, I came across a detail that caused an error when searching for a file that was inside a nested pack.
Imagine this scenario
```
app/
- cells/
config/
...
packs/
- base_pack/ --- This is a pack
- app/
- cells/
- controllers/
- models/
- ...
- config
- nested_pack/ --- This is another pack
- app/
- cells/
- test_cell.rb
- controllers
- models/
- other_nested_pack/ -- This is another pack
- app/
- cells/
- test_cell.rb
```
In order to make the [Cells](https://github.com/trailblazer/cells) work, we had to add a function that finds the pack where the cell is stored by using the `.find` method in `Stimpack::Packs`
When this function searched for the `test_cell.rb` this is what was going on:
```ruby
file = …
```
=> Search file in packs beginning with nested packs

README.md, lib/stimpack.rb, lib/stimpack/integrations/factory_bot.rb, lib/stimpack/integrations/rails.rb, lib/stimpack/integrations/rspec.rb, lib/stimpack/pack.rb, lib/stimpack/packs.rb, lib/stimpack/railtie.rb, lib/stimpack/rspec.rb, lib/stimpack/version.rb, spec/stimpack_spec.rb
This PR refactors Stimpack and breaks the initialization step into 2 process: non-Rails and Rails. The non-rails part simply provides packs and pack traversal. When Rails is involved, we inject the packs into Rails (along with Engine support). This helps us extract the RSpec helper so that it works without Rails booting.
Fixes #15
For better RSpec support, you now have to `--require stimpack/rspec`. You can add this to `.rspec` or add it to your command line: `bundle exec rspec --require stimpack/rspec ...`
This allows Stimpack to hook into RSpec before files are resolved. Because of this, we're now able to do some fancy stuff:
(This assumes you've added `--require stimpack/rspec` to `.rspec`)
```
bundle exec rspec #=> Runs _all_ specs in your entire application (packs and all)
bundle …
```
=> Refactor internals and improve RSpec support

README.md
Include additional information in the README on how to correctly integrate Stimpack with `parallel_tests` and `knapsack`. Fixes #30
=> Include parallel test libraries integration docs

lib/stimpack.rb, lib/stimpack/integrations/factory_bot.rb, lib/stimpack/integrations/rails.rb, lib/stimpack/integrations/rspec.rb, lib/stimpack/version.rb, sorbet/rbi/gems/packs@0.0.4.rbi
This PR bumps `packs`, which allows:
- `Stimpack` to configure `packs` directly
- `packs.yml` to take precedence for `packs` configuration if the user is using it, making `stimpack`'s configuration of `packs` a no-op.
=> Allow packs configuration to be set in one place

lib/stimpack/integrations/factory_bot.rb, lib/stimpack/integrations/rails.rb, lib/stimpack/version.rb, sorbet/rbi/gems/packs@0.0.6.rbi, spec/spec_helper.rb, spec/stimpack_spec.rb
Now that `stimpack` uses `packs`, which can be gems, we want to explicitly ignore gems when adding load paths.
If a gem wants to add a load path to a Rails application, it can just make itself an engine, which is the standard supported way to integrate a co    mponent into a rails application.
=> Skip gems when adding load paths

lib/packs/rails/version.rb, packs-rails.gemspec
Currently, repository has a file `LICENSE`, which references MIT license for the library.
In addition, it fixes the links on the Rubygems website:
=> Added gem license to the metadata

README.md, lib/packs/rails/integrations/rails.rb
Hoping to contribute some small improvements related to rails routing on older rails version 6.0. I ran into a few errors in a rails 6.0.x app, hopefully this saves some pain for others.
https://github.com/rails/rails/blob/6-1-stable/actionpack/CHANGELOG.md and https://github.com/rails/rails/pull/37892/files 
The errors I got were:
* Error that the `@app.paths['config/routes']` is nil. This is "fixed" by skipping that path or any other nil paths when injecting paths
* Error that `draw` function is undefined when calling it in root routes.rb file. I added a note in README about requiring rails 6.1 for this function.
Open to feedback on approach
=> Docs/fix for rails 6.0

README.md, lib/packs/rails/integrations/rails.rb, spec/fixtures/rails-7.0/packs/pants/jeans/app/models/pants/jeans/bootcut.rb, spec/fixtures/rails-7.0/packs/pants/jeans/package.yml, spec/packs-rails_spec.rb
I've needed a possibility to set a custom engine namespace to create different engines with same package folder name.
Currently the following package structure creates the same engine `Authentication::Engine`
```yml
metadata:
engine: true
metadata:
engine: true
```
Now it's possible to set a custom engine name to prevent this issue. 
```yml
metadata:
engine: true
engine_name: backend/authentication
metadata:
engine: true
engine_name: frontend/authentication
```
This will generate the following engines: `Backend::Authentication::Engine` and `Frontend::Authentication::Engine`
I think it is better to specify the name explicitly instead of generating the package name based on the folder structure.
=> Added possibility to set custom engine name

README.md
The routes in `config/routes/*.rb` should not include `Rails.application.routes.draw` block, see [Rails Routing from the Outside In: Breaking Up Very Large Route File into Multiple Small Ones](https://guides.rubyonrails.org/routing.html#breaking-up-very-large-route-file-into-multiple-small-ones)
Corresponding thread in Slack: [#rubyatscale](https://rubymod.slack.com/archives/C052KFB2AQP/p1699900913457459)
Closes https://github.com/rubyatscale/packs-rails/issues/69
=> Update routes documentation in README.md

lib/packs/rails/integrations/factory_bot.rb, lib/packs/rails/railtie.rb
Fixes #68.
Trying to make the integration work with Minitest I realized the paths were never added because `app.config.respond_to?(:factory_bot)` always returned `false`.
If this is moved in the railtie to a `config.after_initialize` then it works as expected.
I could not write tests since I didn't find any, I am hoping to get advice on how to do these tests here :wink: 
What I did was:
```shell
bin/rails test some_test.rb # it has a binding.pry
[
[0] "factories",
[1] "test/factories",
[2] "spec/factories"
]
```
In that list we should also see every pack path + "spec/factories", but it is not there.
With this fix it will work as expected, and it will also support minitest folder structure `test/factories`.
=> Fix factory bot integration and add minitest support

README.md
Please feel free to suggest different/better wording.
see PR #76 which prompted this update for context.
=> Update README.md to add clarification on the factorybot integration

README.md
Since packwerk 2.3.0, deprecated_references.yml has been renamed to package_todo.yml. https://github.com/Shopify/packwerk/pull/242
Therefore, packs-rails needs to be renamed as well to avoid confusion for new packwerk users.
=> Rename deprecated_references.yml to package_todo.yml

lib/packs/rails/railtie.rb
https://github.com/rubyatscale/packs-rails/pull/71 breaks gusto's build. By loading factories earlier in the lifecycle, we see more? full? success.
@matiaseche would you check out if this branch works for your use case?
=> Revert to FactoryBot initialization without Rails lifecycle methods (was: Create factories earlier in the lifecycle)

README.md
Fixes https://github.com/rubyatscale/packs-rails/issues/67
=> add a reference to automatic namespaces in the readme

README.md
When a pack moves, some users will want spring to update the loaded classes so that packwerk prints correct results
This is an alternative PR to #82 which started to need more and more gem dependencies.
Fixes #81
=> Add spring watch directions

README.md
It previously wasn't clear why you would make something an engine, as this project reimplements part of Rails::Engine's functionality anyway.
The details were stolen from @ngan 's response in https://github.com/rubyatscale/packs-rails/discussions/14.
This still seems a little bit like bending over backwards to me; why isn't every pack an engine by default? Namespace isolation is just one of many engine features and could be off by default.
=> Add more detail to engine documentation

README.md
Addressing https://github.com/rubyatscale/packs-rails/issues/91
By default, some rubocop-rails `include` globs target `app/...`. 
Including examples of how to override rubocop-rails `Include` globs.
=> mentioning the need for overriding rubocop-rails rules

.github/workflows/cd.yml
Utilizes the shared-config workflow for the CD pipeline.
This repo doesn't have rubocop. I think we can add it and then use the shared config CI pipeline as well.
=> use shared-config for CD workflow
